;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	TeX-insert-backslash
	back-to-indentation-or-beginning
	electric-newline-and-maybe-indent
	ess-smart-comma
	ess-yank
	forward-sexp
	helm-M-x
	keyboard-quit
	kill-region
	mc/mark-all-in-region-regexp
	next-buffer
	wdired-abort-changes
	))

(setq mc/cmds-to-run-once
      '(
	LaTeX-babel-insert-hyphen
	dired-unmark-backward
	previous-buffer
	smart-kill-whole-line
	))
