;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	TeX-insert-backslash
	ess-smart-comma
	ess-yank
	forward-sexp
	keyboard-quit
	kill-region
	next-buffer
	wdired-abort-changes
	))

(setq mc/cmds-to-run-once
      '(
	dired-unmark-backward
	previous-buffer
	smart-kill-whole-line
	))
