;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	TeX-insert-backslash
	TeX-insert-dollar
	TeX-insert-sub-or-superscript
	abbrev-prefix-mark
	back-to-indentation-or-beginning
	backward-sexp
	electric-newline-and-maybe-indent
	end-of-buffer
	ess-smart-S-assign
	ess-smart-comma
	ess-yank
	forward-sexp
	helm-M-x
	helm-show-kill-ring
	helm-swoop
	indent-for-tab-command
	keyboard-quit
	kill-region
	mc/mark-all-in-region-regexp
	next-buffer
	outshine-kbd-TAB
	outshine-self-insert-command
	query-replace
	wdired-abort-changes
	zap-up-to-char
	))

(setq mc/cmds-to-run-once
      '(
	LaTeX-babel-insert-hyphen
	dired-unmark-backward
	ess-eval-region-or-function-or-paragraph-and-step
	magit-status
	mouse-set-region
	previous-buffer
	smart-kill-whole-line
	))
