(defun my-color-theme ()
  "Color theme by Yvan Richard, created 2011-11-02."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "#444444")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "white")
      (foreground-color . "white")
      (mouse-color . "black"))
     ((goto-address-mail-face . italic)
      (goto-address-mail-mouse-face . secondary-selection)
      (goto-address-url-face . bold)
      (goto-address-url-mouse-face . highlight)
      (hl-line-face . hl-line)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . bold)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "#222222" :foreground "cornsilk" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
     (Info-title-1-face ((t (:bold t :weight bold :height 1.728 :family "helv"))))
     (Info-title-2-face ((t (:bold t :weight bold :height 1.44 :family "helv"))))
     (Info-title-3-face ((t (:bold t :weight bold :height 1.2 :family "helv"))))
     (Info-title-4-face ((t (:bold t :weight bold :family "helv"))))
     (bbdb-company ((t (:italic t :slant italic))))
     (bbdb-field-name ((t (:bold t :weight bold))))
     (bbdb-field-value ((t (nil))))
     (bbdb-name ((t (:underline t))))
     (blank-space-face ((t (:background "LightGray"))))
     (blank-tab-face ((t (:background "cornsilk" :foreground "black"))))
     (bold ((t (:bold t :foreground "white" :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (:background "black"))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (calendar-today-face ((t (:underline t))))
     (change-log-acknowledgement-face ((t (:italic t :foreground "AntiqueWhite3" :slant oblique))))
     (change-log-conditionals-face ((t (:foreground "Aquamarine"))))
     (change-log-date-face ((t (:italic t :foreground "BurlyWood" :slant oblique))))
     (change-log-email-face ((t (:foreground "Aquamarine"))))
     (change-log-file-face ((t (:bold t :foreground "LightSkyBlue" :weight bold :height 0.9 :family "Verdana"))))
     (change-log-function-face ((t (:foreground "Aquamarine"))))
     (change-log-list-face ((t (:foreground "LightSkyBlue"))))
     (change-log-name-face ((t (:bold t :foreground "Gold" :weight bold))))
     (clear-case-mode-string-face ((t (:bold t :background "grey" :foreground "black" :box (:line-width 2 :color "grey" :style released-button) :weight bold :height 0.9 :family "Arial"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan"))))
     (completions-common-part ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "cornsilk" :background "black" :stipple nil :height 98))))
     (completions-first-difference ((t (:bold t :weight bold :foreground "white"))))
     (cperl-array-face ((t (:bold t :background "lightyellow2" :foreground "Blue" :weight bold))))
     (cperl-hash-face ((t (:italic t :bold t :background "lightyellow2" :foreground "Red" :slant italic :weight bold))))
     (cperl-nonoverridable-face ((t (:foreground "chartreuse3"))))
     (cursor ((t (:background "white"))))
     (custom-button-face ((t (:background "lightgrey" :foreground "white" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed-face ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-changed-face ((t (:background "skyblue" :foreground "wheat"))))
     (custom-comment-face ((t (:background "dim gray"))))
     (custom-comment-tag-face ((t (:foreground "gray80"))))
     (custom-documentation-face ((t (:foreground "white"))))
     (custom-face-tag-face ((t (:bold t :foreground "white" :underline t :weight bold :height 1.1 :family "helv"))))
     (custom-group-tag-face ((t (:bold t :foreground "skyblue" :underline t :weight bold :height 1.1 :family "helv"))))
     (custom-group-tag-face-1 ((t (:bold t :foreground "pink" :underline t :weight bold :height 1.1 :family "helv"))))
     (custom-invalid-face ((t (:background "red" :foreground "yellow"))))
     (custom-modified-face ((t (:background "blue" :foreground "white"))))
     (custom-rogue-face ((t (:background "black" :foreground "pink"))))
     (custom-saved-face ((t (:underline t))))
     (custom-set-face ((t (:background "white" :foreground "blue"))))
     (custom-state-face ((t (:foreground "light green"))))
     (custom-variable-button-face ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag-face ((t (:bold t :foreground "skyblue" :underline t :weight bold :height 1.2 :family "helv"))))
     (diary-face ((t (:bold t :foreground "orange" :weight bold))))
     (diff-added-face ((t (nil))))
     (diff-changed-face ((t (nil))))
     (diff-context-face ((t (:foreground "grey70"))))
     (diff-file-header-face ((t (:bold t :background "grey60" :weight bold))))
     (diff-function-face ((t (:foreground "grey70"))))
     (diff-header-face ((t (:background "grey45"))))
     (diff-hunk-header-face ((t (:background "grey45"))))
     (diff-index-face ((t (:bold t :background "grey60" :weight bold))))
     (diff-nonexistent-face ((t (:bold t :background "grey60" :weight bold))))
     (diff-removed-face ((t (nil))))
     (escape-glyph ((t (:foreground "cyan"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed-pitch ((t (:family "courier"))))
     (font-lock-builtin-face ((t (:bold t :foreground "LightSteelBlue" :weight bold))))
     (font-lock-comment-delimiter-face ((t (:italic t :slant italic :foreground "red"))))
     (font-lock-comment-face ((t (:italic t :foreground "#AA1111" :slant italic))))
     (font-lock-constant-face ((t (:bold t :foreground "salmon" :weight bold))))
     (font-lock-doc-face ((t (:italic t :foreground "BurlyWood" :slant oblique))))
     (font-lock-doc-string-face ((t (:italic t :foreground "BurlyWood" :slant oblique))))
     (font-lock-function-name-face ((t (:bold t :foreground "orange" :weight bold :height 0.9 :family "Verdana"))))
     (font-lock-keyword-face ((t (:bold t :foreground "#BF6A0D" :weight bold))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:bold t :foreground "Gold" :weight bold))))
     (font-lock-reference-face ((t (:foreground "SteelBlue"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold :foreground "white"))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold :foreground "white"))))
     (font-lock-string-face ((t (:italic t :foreground "wheat" :slant normal))))
     (font-lock-type-face ((t (:bold t :foreground "navajowhite" :weight normal :height 1.0 :family "DejaVu Sans Mono"))))
     (font-lock-variable-name-face ((t (:italic t :bold t :foreground "light salmon" :slant italic :weight bold))))
     (font-lock-warning-face ((t (:bold t :foreground "gold" :weight bold))))
     (fringe ((t (:stipple nil :background "grey4" :foreground "Wheat" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "courier new"))))
     (gnus-cite-attribution-face ((t (:italic t :slant italic))))
     (gnus-cite-face-1 ((t (:foreground "light cyan"))))
     (gnus-cite-face-10 ((t (:foreground "medium purple"))))
     (gnus-cite-face-11 ((t (:foreground "turquoise"))))
     (gnus-cite-face-2 ((t (:foreground "light blue"))))
     (gnus-cite-face-3 ((t (:foreground "light yellow"))))
     (gnus-cite-face-4 ((t (:foreground "light pink"))))
     (gnus-cite-face-5 ((t (:foreground "pale green"))))
     (gnus-cite-face-6 ((t (:foreground "beige"))))
     (gnus-cite-face-7 ((t (:foreground "orange"))))
     (gnus-cite-face-8 ((t (:foreground "magenta"))))
     (gnus-cite-face-9 ((t (:foreground "violet"))))
     (gnus-emphasis-bold ((t (:bold t :weight bold))))
     (gnus-emphasis-bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (gnus-emphasis-highlight-words ((t (:background "black" :foreground "yellow"))))
     (gnus-emphasis-italic ((t (:italic t :slant italic))))
     (gnus-emphasis-underline ((t (:background "goldenrod4" :foreground "white" :underline t))))
     (gnus-emphasis-underline-bold ((t (:bold t :background "yellow" :foreground "black" :underline t :weight bold))))
     (gnus-emphasis-underline-bold-italic ((t (:italic t :bold t :background "yellow" :foreground "black" :underline t :slant italic :weight bold))))
     (gnus-emphasis-underline-italic ((t (:italic t :background "yellow" :foreground "black" :underline t :slant italic))))
     (gnus-filterhist-face-1 ((t (nil))))
     (gnus-group-mail-1-empty-face ((t (:foreground "gray80"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "white" :weight bold))))
     (gnus-group-mail-2-empty-face ((t (:foreground "lightcyan"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "lightcyan" :weight bold))))
     (gnus-group-mail-3-empty-face ((t (:foreground "tan"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "tan" :weight bold))))
     (gnus-group-mail-low-empty-face ((t (:foreground "aquamarine4"))))
     (gnus-group-mail-low-face ((t (:bold t :foreground "aquamarine4" :weight bold))))
     (gnus-group-news-1-empty-face ((t (:foreground "white"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "white" :weight bold))))
     (gnus-group-news-2-empty-face ((t (:foreground "lightcyan"))))
     (gnus-group-news-2-face ((t (:bold t :foreground "lightcyan" :weight bold))))
     (gnus-group-news-3-empty-face ((t (:foreground "tan"))))
     (gnus-group-news-3-face ((t (:bold t :foreground "tan" :weight bold))))
     (gnus-group-news-4-empty-face ((t (:foreground "white"))))
     (gnus-group-news-4-face ((t (:bold t :foreground "white" :weight bold))))
     (gnus-group-news-5-empty-face ((t (:foreground "wheat"))))
     (gnus-group-news-5-face ((t (:bold t :foreground "wheat" :weight bold))))
     (gnus-group-news-6-empty-face ((t (:foreground "tan"))))
     (gnus-group-news-6-face ((t (:bold t :foreground "tan" :weight bold))))
     (gnus-group-news-low-empty-face ((t (:foreground "DarkTurquoise"))))
     (gnus-group-news-low-face ((t (:bold t :foreground "DarkTurquoise" :weight bold))))
     (gnus-header-content-face ((t (:italic t :foreground "plum1" :slant italic))))
     (gnus-header-from-face ((t (:bold t :foreground "wheat" :weight bold))))
     (gnus-header-name-face ((t (:bold t :foreground "gold" :weight bold))))
     (gnus-header-newsgroups-face ((t (:italic t :bold t :foreground "wheat" :slant italic :weight bold))))
     (gnus-header-subject-face ((t (:bold t :foreground "red" :weight bold))))
     (gnus-signature-face ((t (:italic t :foreground "maroon" :slant italic))))
     (gnus-splash ((t (:foreground "Brown"))))
     (gnus-splash-face ((t (:foreground "gold"))))
     (gnus-summary-cancelled-face ((t (:background "gray" :foreground "black"))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "SkyBlue" :weight bold))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "gray70" :weight bold))))
     (gnus-summary-high-unread-face ((t (:italic t :bold t :slant italic :weight bold))))
     (gnus-summary-low-ancient-face ((t (:italic t :foreground "SkyBlue" :slant italic))))
     (gnus-summary-low-read-face ((t (:italic t :foreground "PaleGreen" :slant italic))))
     (gnus-summary-low-ticked-face ((t (:italic t :bold t :foreground "gray70" :slant italic :weight bold))))
     (gnus-summary-low-unread-face ((t (:italic t :slant italic))))
     (gnus-summary-normal-ancient-face ((t (:foreground "SkyBlue"))))
     (gnus-summary-normal-read-face ((t (:foreground "PaleGreen"))))
     (gnus-summary-normal-ticked-face ((t (:bold t :foreground "gray70" :weight bold))))
     (gnus-summary-normal-unread-face ((t (:bold t :weight bold))))
     (gnus-summary-selected-face ((t (:background "deepskyblue4" :underline t))))
     (header-line ((t (:background "grey20" :foreground "grey75" :box (:line-width 3 :color "grey20" :style released-button) :height 0.81 :family "Arial"))))
     (help-argument-name ((t (:italic t :slant italic))))
     (highlight ((t (:background "darkslategray" :foreground "wheat"))))
     (highlight-changes-delete-face ((t (:foreground "red" :underline t))))
     (highlight-changes-face ((t (:foreground "red"))))
     (highline-face ((t (:background "gray35"))))
     (hl-line ((t (:foreground "wheat" :background "darkslategray"))))
     (holiday-face ((t (:background "red"))))
     (info-header-node ((t (:italic t :bold t :foreground "white" :slant italic :weight bold))))
     (info-header-xref ((t (:bold t :foreground "cyan" :weight bold))))
     (info-menu-5 ((t (:foreground "red1" :underline t))))
     (info-menu-header ((t (:bold t :weight bold :family "helv"))))
     (info-node ((t (:italic t :bold t :foreground "yellow" :slant italic :weight bold))))
     (info-xref ((t (:bold t :foreground "plum" :weight bold))))
     (isearch ((t (:background "palevioletred2" :foreground "brown4"))))
     (isearch-fail ((t (:background "red4"))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "paleturquoise4"))))
     (lazy-highlight-face ((t (:bold t :foreground "dark magenta" :weight bold))))
     (linemenu-face ((t (:background "gray30"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (makefile-space-face ((t (:background "hotpink"))))
     (match ((t (:background "RoyalBlue3"))))
     (menu ((t (nil))))
     (message-cited-text-face ((t (:foreground "plum1"))))
     (message-header-cc-face ((t (:bold t :foreground "ivory" :weight bold))))
     (message-header-name-face ((t (:foreground "light sky blue"))))
     (message-header-newsgroups-face ((t (:italic t :bold t :foreground "lavender blush" :slant italic :weight bold))))
     (message-header-other-face ((t (:foreground "pale turquoise"))))
     (message-header-subject-face ((t (:bold t :foreground "papaya whip" :weight bold))))
     (message-header-to-face ((t (:bold t :foreground "floral white" :weight bold))))
     (message-header-xheader-face ((t (:foreground "blue"))))
     (message-mml-face ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (message-separator-face ((t (:foreground "sandy brown"))))
     (minibuffer-prompt ((t (:foreground "cyan"))))
     (mode-line ((t (:background "tan" :foreground "black" :box (:line-width 2 :color "grey" :style released-button) :height 0.9 :family "Arial"))))
     (mode-line-buffer-id ((t (:background "tan" :foreground "black" :box (:line-width 2 :color "grey" :style released-button) :height 0.9 :family "Arial"))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:family "Arial" :background "grey30" :foreground "grey80" :box (:line-width -1 :color "grey40" :style nil) :weight light :height 0.9))))
     (modeline-mousable ((t (:background "tan" :foreground "black" :box (:line-width 2 :color "grey" :style released-button) :height 0.9 :family "Arial"))))
     (modeline-mousable-minor-mode ((t (:background "tan" :foreground "black" :box (:line-width 2 :color "grey" :style released-button) :height 0.9 :family "Arial"))))
     (mouse ((t (:background "black"))))
     (next-error ((t (:background "slategrey"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (paren-mismatch-face ((t (:bold t :background "white" :foreground "red" :weight bold))))
     (paren-no-match-face ((t (:bold t :background "white" :foreground "red" :weight bold))))
     (primary-selection ((t (:background "DarkSlateGray"))))
     (query-replace ((t (:foreground "brown4" :background "palevioletred2"))))
     (region ((t (:background "slategrey"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "deepskyblue4"))))
     (sgml-doctype-face ((t (:foreground "orange"))))
     (sgml-end-tag-face ((t (:foreground "greenyellow"))))
     (sgml-entity-face ((t (:foreground "gold"))))
     (sgml-ignored-face ((t (:background "gray60" :foreground "gray20"))))
     (sgml-sgml-face ((t (:foreground "yellow"))))
     (sgml-start-tag-face ((t (:foreground "mediumspringgreen"))))
     (shadow ((t (:foreground "grey70"))))
     (show-paren-match ((t (:background "deepskyblue4"))))
     (show-paren-match-face ((t (:background "deepskyblue4"))))
     (show-paren-mismatch ((t (:bold t :background "red" :foreground "white" :weight bold))))
     (show-paren-mismatch-face ((t (:bold t :background "red" :foreground "white" :weight bold))))
     (speedbar-button-face ((t (:foreground "green4"))))
     (speedbar-directory-face ((t (:foreground "blue4"))))
     (speedbar-file-face ((t (:bold t :foreground "cyan4" :weight bold))))
     (speedbar-highlight-face ((t (:background "green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-tag-face ((t (:foreground "brown"))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "helv" :background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "white"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "helv"))))
     (vertical-border ((t (nil))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "gray20"))))
     (widget-inactive ((t (:foreground "wheat"))))
     (widget-single-line-field ((t (:background "gray20"))))
     (woman-bold-face ((t (:bold t :weight bold))))
     (woman-italic-face ((t (:foreground "beige"))))
     (woman-unknown-face ((t (:foreground "LightSalmon"))))
     (zmacs-region ((t (:background "DarkSlateGray")))))))
