(deftheme sanityinc-tomorrow-night
  "Created 2015-03-03.")

(custom-theme-set-variables
 'sanityinc-tomorrow-night
 '(ansi-color-names-vector ["#c5c8c6" "#cc6666" "#b5bd68" "#f0c674" "#81a2be" "#b294bb" "#8abeb7" "#1d1f21"])
 '(ansi-color-faces-vector [default bold shadow italic underline bold bold-italic bold]))

(custom-theme-set-faces
 'sanityinc-tomorrow-night
 '(bold ((((class color) (min-colors 89)) (:weight bold))))
 '(bold-italic ((((class color) (min-colors 89)) (:slant italic :weight bold))))
 '(underline ((((class color) (min-colors 89)) (:underline t))))
 '(italic ((((class color) (min-colors 89)) (:slant italic))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#969896" :slant italic))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#969896" :slant italic))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#f0c674"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#8abeb7"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#f0c674"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "#cc6666"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#cc6666"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) (:foreground "#c5c8c6"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) (:foreground "#8abeb7"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) (:foreground "#f0c674"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) (:foreground "#c5c8c6"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) (:foreground "#8abeb7"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) (:foreground "#f0c674"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) (:foreground "#cc6666"))))
 '(match ((((class color) (min-colors 89)) (:foreground "#81a2be" :background "#1d1f21" :inverse-video t))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#f0c674" :background "#1d1f21" :inverse-video t))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#8abeb7" :background "#1d1f21" :inverse-video t))))
 '(isearch-fail ((((class color) (min-colors 89)) (:background "#1d1f21" :inherit font-lock-warning-face :inverse-video t))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(ido-indicator ((((class color) (min-colors 89)) (:foreground "#cc6666" :background "#1d1f21"))))
 '(ido-virtual ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(flx-highlight-face ((((class color) (min-colors 89)) (:inherit nil :foreground "#f0c674" :weight bold :underline nil))))
 '(cursor ((((class color) (min-colors 89)) (:background "#cc6666"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#373b41"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#282a2e"))))
 '(border ((((class color) (min-colors 89)) (:background "#373b41" :foreground "#373b41"))))
 '(highlight ((((class color) (min-colors 89)) (:inverse-video nil :background "#282a2e"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground nil :background "#373b41" :weight normal :box (:line-width 1 :color "#969896")))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:foreground "#b294bb" :background nil))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#969896" :background "#373b41" :weight normal :box (:line-width 1 :color "#373b41")))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:foreground "#c5c8c6" :slant italic))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:foreground "#b294bb" :box nil :weight bold))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(region ((((class color) (min-colors 89)) (:background "#373b41" :inverse-video nil))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#282a2e"))))
 '(header-line ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#b294bb" :background nil))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#cc6666" :foreground "#f0c674"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:background "#b294bb" :foreground "#1d1f21"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:background "#cc6666" :foreground "#1d1f21"))))
 '(sh-heredoc ((((class color) (min-colors 89)) (:foreground nil :inherit font-lock-string-face :weight normal))))
 '(sh-quoted-exec ((((class color) (min-colors 89)) (:foreground nil :inherit font-lock-preprocessor-face))))
 '(csv-separator-face ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "#b5bd68" :weight bold))))
 '(link ((((class color) (min-colors 89)) (:foreground nil :underline t))))
 '(widget-button ((((class color) (min-colors 89)) (:underline t))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#373b41" :box (:line-width 1 :color "#c5c8c6")))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:foreground "#f0c674"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#f0c674"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "#cc6666"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(helm-buffer-saved-out ((((class color) (min-colors 89)) (:inherit warning))))
 '(helm-buffer-size ((((class color) (min-colors 89)) (:foreground "#f0c674"))))
 '(helm-buffer-not-saved ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(helm-buffer-process ((((class color) (min-colors 89)) (:foreground "#8abeb7"))))
 '(helm-buffer-directory ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(helm-ff-directory ((((class color) (min-colors 89)) (:foreground "#8abeb7"))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:foreground "#cc6666"))))
 '(helm-selection ((((class color) (min-colors 89)) (:inherit highlight))))
 '(helm-separator ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 '(helm-source-header ((((class color) (min-colors 89)) (:weight bold :foreground "#de935f" :height 1.44))))
 '(company-preview ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:inherit company-preview :foreground "#cc6666"))))
 '(company-preview-search ((((class color) (min-colors 89)) (:inherit company-preview :foreground "#81a2be"))))
 '(company-tooltip ((((class color) (min-colors 89)) (:background "#373b41"))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:background "#282a2e"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:inherit company-tooltip :foreground "#cc6666"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:inherit company-tooltip-selection :foreground "#cc6666"))))
 '(company-tooltip-search ((((class color) (min-colors 89)) (:inherit company-tooltip :foreground "#81a2be"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:inherit company-tooltip :foreground "#b5bd68"))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:inherit (quote company-tooltip) :background "#282a2e"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:background "#373b41"))))
 '(company-echo-common ((((class color) (min-colors 89)) (:inherit company-echo :foreground "#cc6666"))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#81a2be" :underline nil))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#f0c674"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#373b41"))))
 '(org-column-title ((((class color) (min-colors 89)) (:inherit org-column :weight bold :underline t))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#81a2be" :underline t))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#8abeb7"))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(org-document-title ((((class color) (min-colors 89)) (:weight bold :foreground "#de935f" :height 1.44))))
 '(org-done ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(org-footnote ((((class color) (min-colors 89)) (:foreground "#8abeb7"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#cc6666"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#1d1f21" :background "#1d1f21"))))
 '(org-link ((((class color) (min-colors 89)) (:foreground "#81a2be" :underline t))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#b294bb"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#cc6666"))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#de935f"))))
 '(org-warning ((((class color) (min-colors 89)) (:weight bold :foreground "#cc6666"))))
 '(hl-sexp-face ((((class color) (min-colors 89)) (:background "#373b41"))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit nil :foreground "#81a2be"))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit nil :foreground "#b294bb"))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit nil :foreground "#8abeb7"))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit nil :foreground "#f0c674"))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit nil :foreground "#de935f"))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit nil :foreground "#81a2be"))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit nil :foreground "#b294bb"))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit nil :foreground "#8abeb7"))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:foreground "#81a2be"))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#b5bd68"))))
 '(default ((t (:background "#1d1f21" :foreground "#dddddd")))))

(provide-theme 'sanityinc-tomorrow-night)
